version: 0.0
os: linux
files:
  - source: /bin
    destination: /var/www/html
  - source: /composer.json
    destination: /var/www/html/composer.json
  - source: /composer.lock
    destination: /var/www/html/composer.lock
  - source: /cr.json
    destination: /var/www/html/composer.json
  - source: /nginx.conf
    destination: /var/www/html
  - source: /operators.json
    destination: /var/www/html/operators.json
  - source: /phpunit.xml.dist
    destination: /var/www/html/phpunit.xml.dist
  - source: /public
    destination: /var/www/html
  - source: /src   
    destination: /var/www/html 
  - source: /support.json
    destination: /var/www/html/support.json
  - source: /sympony.lock
    destination: /var/www/html/symphony.lock
  - source: /templates
    destination: /var/www/html/templates
hooks:
   BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
   ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
