version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
  # - source: /app
  #   destination: /var/www/html
  # - source: /artisan
  #   destination: /var/www/html
  # - source: /bootstrap
  #   destination: /var/www/html
  # - source: /composer.json
  #   destination: /var/www/html
  # - source: /composer.lock
  #   destination: /var/www/html
  # - source: /database
  #   destination: /var/www/html
  # - source: /logs
  #   destination: /var/www/html
  # - source: /nginx.config
  #   destination: /var/www/html
  # - source: /phpunit.xml
  #   destination: /var/www/html 
  # - source: /public
  #   destination: /var/www/html
  # - source: /resources
  #   destination: /var/www/html
  # - source: /routes
  #   destination: /var/www/html
  # - source: /scripts
  #   destination: /var/www/html
  # - source: /storage
  #   destination: /var/www/html
  # - source: /tests
  #   destination: /var/www/html	
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/composer_install.sh
      timeout: 300
      runas: root
